service: tweet-etl-serverless

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: non-linux
  dbConn: ${ssm:tweet-sentiment-redshift-conn}

frameworkVersion: '2'

provider:
  name: aws
  runtime: python3.8
  region: eu-west-1
  timeout: 300
  environment:
    DB_CONN: ${self.custom.dbConn}
  vpc:
    securityGroupIds:
      - sg-8a520bc3
    subnetIds:
      - subnet-2ed14674
  iamRoleStatements:
    - Effect: Allow
      Action:
        - "ec2:CreateNetworkInterface"
      Resource: "*"

functions:
  etl:
    handler: handler.main
    events:
      - schedule: rate(1 hour)
