service: tweet-etl-serverless

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: non-linux
  dbConn: ${ssm:tweet-sentiment-redshift-conn}
  twitterConsumerKey: ${ssm:twitter-consumer-key}
  twitterConsumerSecret: ${ssm:twitter-consumer-secret}
  twitterAccessToken: ${ssm:twitter-access-token}
  twitterAccessSecret: ${ssm:twitter-access-token-secret}

frameworkVersion: '2'

provider:
  name: aws
  runtime: python3.8
  region: eu-west-1
  timeout: 900
  environment:
    DB_CONN: ${self:custom.dbConn}
    TWITTER_CONSUMER_KEY: ${self:custom.twitterConsumerKey}
    TWITTER_CONSUMER_SECRET: ${self:custom.twitterConsumerSecret}
    TWITTER_ACCESS_TOKEN: ${self:custom.twitterAccessToken}
    TWITTER_ACCESS_SECRET: ${self:custom.twitterAccessSecret}
  vpc:
    securityGroupIds:
      - sg-8a520bc3
    subnetIds:
      - subnet-0544233cb32321b29
      - subnet-07822b9c9cf15b5f8
      - subnet-0a6b8641af20c3163
  iamRoleStatements:
    - Effect: "Allow"
      Action: 
      - "ec2:CreateNetworkInterface"
      Resource: "*"
      

functions:
  etl:
    handler: handler.main
    events:
      - schedule: rate(1 hour)
